// 全局常量：订单状态机 + WebSocket 信令（与后端严格对齐，FRD §1.3）
const ORDER_STATUS = {
  PENDING: 0, WAITING: 1, CONSULTING: 2, AUDITING: 3, REJECTED: 4,
  PRESCRIBED: 5, FINISHED: 6, REFUNDED: 7, CANCELLED: 9
};

const SIGNAL = {
  INIT_CALL: 'INIT_CALL',
  CALL_INVITE: 'CALL_INVITE',
  CALL_REJECT: 'CALL_REJECT',
  CALL_ANSWER: 'CALL_ANSWER',
  CALL_FINISHED: 'CALL_FINISHED',
  START_STREAM: 'START_STREAM',
  QUEUE_UPDATE: 'QUEUE_UPDATE',
  CHAT_MESSAGE: 'CHAT_MESSAGE'
};

module.exports = { ORDER_STATUS, SIGNAL };
